# Generated by Django 2.2.3 on 2019-07-02 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddressBook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddressEntry',
            new_name='Contact',
        ),
    ]
