# Generated by Django 2.2.3 on 2019-07-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddressBook', '0002_auto_20190701_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
